title: jernoble.github.io
email: jer.noble@apple.com
description: >- # this means to ignore newlines until "baseurl:"
  Sites published on GitHub Pages
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jernoble.github.io"
repo_url: "https://jernoble.github.io/"

# Build settings
markdown: kramdown

tipue_search:
  include:
    pages: true

theme: jekyll-theme-minimal
